MVC_EFCF/Models/ErrorViewModel.cs
namespace MVC_EFCF.Models {
    public class ErrorViewModel {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC_EFCF/Models/TaxDocument.cs
namespace MVC_EFCF.Models {
    public class TaxDocument {
        public long Id { get; set; }
        public long NIT { get; set; }
        public string Name { get; set; } = String.Empty;
        public short DocumentType { get; set; }
        public long DocumentNumber { get; set; }
        public string DocumentComplement { get; set; } = String.Empty;
        public short Currency { get; set; }
        public Decimal TotalAmount { get; set; }
        public List<Detail> Detail { get; set; } = new List<Detail>();
    }
    public class Detail {
        public long IdTaxDocument { get; set; }
        public long Id { get; set; }
        public string Description { get; set; } = String.Empty;
        public int Quantity { get; set; }
        public decimal SingleAmount { get; set; }
        public decimal PartialAmount { get; set; }
        public TaxDocument taxDocument { get; set; } = new TaxDocument();
    }
}

MVC_EFCF/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_EFCF.Models;
using System.Diagnostics;

namespace MVC_EFCF.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC_EFCF/Controllers/TaxDocumentsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_EFCF.Data;
using MVC_EFCF.Models;

namespace MVC_EFCF
{
    public class TaxDocumentsController : Controller
    {
        private readonly MVC_EFCFContext _context;

        public TaxDocumentsController(MVC_EFCFContext context)
        {
            _context = context;
        }

        // GET: TaxDocuments
        public async Task<IActionResult> Index()
        {
            return View(await _context.TaxDocument.ToListAsync());
        }

        // GET: TaxDocuments/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taxDocument = await _context.TaxDocument
                .FirstOrDefaultAsync(m => m.Id == id);
            if (taxDocument == null)
            {
                return NotFound();
            }

            return View(taxDocument);
        }

        // GET: TaxDocuments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TaxDocuments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NIT,Name,DocumentType,DocumentNumber,DocumentComplement,Currency,TotalAmount")] TaxDocument taxDocument)
        {
            if (ModelState.IsValid)
            {
                _context.Add(taxDocument);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(taxDocument);
        }

        // GET: TaxDocuments/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taxDocument = await _context.TaxDocument.FindAsync(id);
            if (taxDocument == null)
            {
                return NotFound();
            }
            return View(taxDocument);
        }

        // POST: TaxDocuments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,NIT,Name,DocumentType,DocumentNumber,DocumentComplement,Currency,TotalAmount")] TaxDocument taxDocument)
        {
            if (id != taxDocument.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(taxDocument);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaxDocumentExists(taxDocument.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(taxDocument);
        }

        // GET: TaxDocuments/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taxDocument = await _context.TaxDocument
                .FirstOrDefaultAsync(m => m.Id == id);
            if (taxDocument == null)
            {
                return NotFound();
            }

            return View(taxDocument);
        }

        // POST: TaxDocuments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var taxDocument = await _context.TaxDocument.FindAsync(id);
            _context.TaxDocument.Remove(taxDocument);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TaxDocumentExists(long id)
        {
            return _context.TaxDocument.Any(e => e.Id == id);
        }
    }
}

MVC_EFCF/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC_EFCF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_EFCF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_EFCF.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_EFCF</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TaxDocuments" asp-action="">TaxDocuments</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC_EFCF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC_EFCF/Views/TaxDocuments/Create.cshtml
@model MVC_EFCF.Models.TaxDocument

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TaxDocument</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NIT" class="control-label"></label>
                <input asp-for="NIT" class="form-control" />
                <span asp-validation-for="NIT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocumentType" class="control-label"></label>
                <input asp-for="DocumentType" class="form-control" />
                <span asp-validation-for="DocumentType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocumentNumber" class="control-label"></label>
                <input asp-for="DocumentNumber" class="form-control" />
                <span asp-validation-for="DocumentNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocumentComplement" class="control-label"></label>
                <input asp-for="DocumentComplement" class="form-control" />
                <span asp-validation-for="DocumentComplement" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Currency" class="control-label"></label>
                <input asp-for="Currency" class="form-control" />
                <span asp-validation-for="Currency" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalAmount" class="control-label"></label>
                <input asp-for="TotalAmount" class="form-control" />
                <span asp-validation-for="TotalAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_EFCF/Views/TaxDocuments/Delete.cshtml
@model MVC_EFCF.Models.TaxDocument

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaxDocument</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NIT)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NIT)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DocumentType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DocumentType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DocumentNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DocumentNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DocumentComplement)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DocumentComplement)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Currency)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Currency)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalAmount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVC_EFCF/Views/TaxDocuments/Details.cshtml
@model MVC_EFCF.Models.TaxDocument

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TaxDocument</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NIT)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NIT)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DocumentType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DocumentType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DocumentNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DocumentNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DocumentComplement)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DocumentComplement)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Currency)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Currency)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalAmount)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVC_EFCF/Views/TaxDocuments/Edit.cshtml
@model MVC_EFCF.Models.TaxDocument

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TaxDocument</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NIT" class="control-label"></label>
                <input asp-for="NIT" class="form-control" />
                <span asp-validation-for="NIT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocumentType" class="control-label"></label>
                <input asp-for="DocumentType" class="form-control" />
                <span asp-validation-for="DocumentType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocumentNumber" class="control-label"></label>
                <input asp-for="DocumentNumber" class="form-control" />
                <span asp-validation-for="DocumentNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocumentComplement" class="control-label"></label>
                <input asp-for="DocumentComplement" class="form-control" />
                <span asp-validation-for="DocumentComplement" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Currency" class="control-label"></label>
                <input asp-for="Currency" class="form-control" />
                <span asp-validation-for="Currency" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalAmount" class="control-label"></label>
                <input asp-for="TotalAmount" class="form-control" />
                <span asp-validation-for="TotalAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_EFCF/Views/TaxDocuments/Index.cshtml
@model IEnumerable<MVC_EFCF.Models.TaxDocument>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NIT)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DocumentType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DocumentNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DocumentComplement)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Currency)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalAmount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NIT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DocumentType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DocumentNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DocumentComplement)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Currency)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalAmount)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>